version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"               # Root-Verzeichnis deines Cargo-Projekts
    schedule:
      interval: "weekly"         # oder "daily", "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    rebase-strategy: "auto"
