name: Draft Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, aarch64-unknown-linux-gnu, x86_64-apple-darwin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename binaries
        run: |
          case "${{ matrix.target }}" in
            x86_64-unknown-linux-gnu)
              cp target/${{ matrix.target }}/release/signum-miner signum-miner
              ;;
            aarch64-unknown-linux-gnu)
              cp target/${{ matrix.target }}/release/signum-miner signum-miner-aarch64
              ;;
            x86_64-apple-darwin)
              zip signum-miner-x86_64-apple-darwin.zip target/${{ matrix.target }}/release/signum-miner
              ;;
            x86_64-pc-windows-gnu)
              cp target/${{ matrix.target }}/release/signum-miner.exe signum-miner.exe
              ;;
          esac

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: signum-miner-${{ matrix.target }}
          path: |
            signum-miner
            signum-miner-aarch64
            signum-miner-x86_64-apple-darwin.zip
            signum-miner.exe
        if: success()

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Copy config.yaml
        run: cp config.yaml config.yaml

      - name: Create draft GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/**/*
            config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}