name: Draft Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # z. B. v1.9.0

jobs:
  build:
    name: Build and Draft Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install aarch64 cross-compiler
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            cp target/${{ matrix.target }}/release/signum-miner.exe artifacts/Signum-miner-${{ matrix.target }}.exe
          else
            cp target/${{ matrix.target }}/release/signum-miner artifacts/Signum-miner-${{ matrix.target }}
          fi
          cp config.yaml artifacts/

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
